name: Publish
on:
  workflow_dispatch:
jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      GH_PAGES: gh-pages
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        ref: master
    - name: Push changes to GH_PAGES branch
      run: |
          git fetch
          git checkout ${{ env.GH_PAGES }}
          git merge --ff --allow-unrelated-histories -X theirs master
    - name: Minify Action
      uses: anthonyftwang/minify-action@v1
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
          commit_message: 'chore(action): push minified changes'
          branch: ${{ env.GH_PAGES }}
