name: Publish
on:
  workflow_dispatch:
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        ref: master
    - name: Push changes to gh-pages
      run: |
          git fetch
          git checkout gh-pages
          git merge --ff -s theirs master
    - name: Minify Action
      uses: anthonyftwang/minify-action@v1
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
          commit_message: 'chore(action): push minified changes'
          branch: gh-pages
